print("")
print("^1Author : ssl3p (discord : ssl3p)^0")
print("")
print("^2[Download] : https://github.com/ssl3p/sBan-waveshield^0")
print("^2[Feature Suggestions] : https://github.com/ssl3p/sBan-waveshield^0")
print("")
print("^6Thank you for your support.^0")
print("")